/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.iecst.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.iecst.parser.antlr.internal.InternalIECSTParser;
import org.xtext.example.iecst.services.IECSTGrammarAccess;

public class IECSTParser extends AbstractAntlrParser {

	@Inject
	private IECSTGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalIECSTParser createParser(XtextTokenStream stream) {
		return new InternalIECSTParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public IECSTGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(IECSTGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
