/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.iecst.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class IECSTUiModule extends AbstractIECSTUiModule {

	public IECSTUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
