/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.iecst.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.iecst.ui.internal.IecstActivator;

public class IECSTUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return IecstActivator.getInstance().getInjector("org.xtext.example.iecst.IECST");
	}

}
