/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.iecst.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.iecst.IECSTRuntimeModule;
import org.xtext.example.iecst.IECSTStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class IECSTIdeSetup extends IECSTStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new IECSTRuntimeModule(), new IECSTIdeModule()));
	}
	
}
