/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.iecst.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.example.iecst.ui.internal.IecstActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class IECSTExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(IecstActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		IecstActivator activator = IecstActivator.getInstance();
		return activator != null ? activator.getInjector(IecstActivator.ORG_XTEXT_EXAMPLE_IECST_IECST) : null;
	}

}
