/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.iecst.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractIECSTScopeProvider extends DelegatingScopeProvider {
}
