/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.iecst.iECST;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.iecst.iECST.Model#getPrograms <em>Programs</em>}</li>
 *   <li>{@link org.xtext.example.iecst.iECST.Model#getFunctions <em>Functions</em>}</li>
 *   <li>{@link org.xtext.example.iecst.iECST.Model#getFunctionb <em>Functionb</em>}</li>
 *   <li>{@link org.xtext.example.iecst.iECST.Model#getTypes <em>Types</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.iecst.iECST.IECSTPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Programs</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.iecst.iECST.Program}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Programs</em>' containment reference list.
   * @see org.xtext.example.iecst.iECST.IECSTPackage#getModel_Programs()
   * @model containment="true"
   * @generated
   */
  EList<Program> getPrograms();

  /**
   * Returns the value of the '<em><b>Functions</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.iecst.iECST.Function}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Functions</em>' containment reference list.
   * @see org.xtext.example.iecst.iECST.IECSTPackage#getModel_Functions()
   * @model containment="true"
   * @generated
   */
  EList<Function> getFunctions();

  /**
   * Returns the value of the '<em><b>Functionb</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.iecst.iECST.FunctionBlock}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Functionb</em>' containment reference list.
   * @see org.xtext.example.iecst.iECST.IECSTPackage#getModel_Functionb()
   * @model containment="true"
   * @generated
   */
  EList<FunctionBlock> getFunctionb();

  /**
   * Returns the value of the '<em><b>Types</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.iecst.iECST.Type}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Types</em>' containment reference list.
   * @see org.xtext.example.iecst.iECST.IECSTPackage#getModel_Types()
   * @model containment="true"
   * @generated
   */
  EList<Type> getTypes();

} // Model
