/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.iecst.scoping;


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class IECSTScopeProvider extends AbstractIECSTScopeProvider {

}
